export const CUENTA_PERDIDAS_GANANCIAS_CONSTANTS = [{
  ingresosExplotacion: 'Ingresos de explotación',
  importeNetoCifraVentas: 'Importe neto cifra de ventas',
  otrosIngresosExplotacion: 'Otros ingresos de explotación',
  trppi: 'TRPPI',
  costesExplotacion: 'Costes de explotación',
  consumoMercaderiasMaterias: 'Consumo de mercaderías y materias',
  gastoPersonal: 'Gasto de personal',
  otrosGastosExplotacion: 'Otros gastos de explotación',
  ebitda: 'EBITDA',
  cat: 'CAT',
  bait: 'BAIT',
  ingresosFinancieros: 'Ingresos financieros',
  gastosFinancieros: 'Gastos financieros',
  resultadoFinanciero: 'Resultado financiero',
  resultadoOrdinarioAntesDeImpuestos: 'Resultado ordinario antes de impuestos',
  impuestoSobreSociedades: 'Impuesto sobre sociedades',
  resultadoActividadesOrdinarias: 'Resultado actividades ordinarias',
  ingresosExtraordinarios: 'Ingresos extraordinarios',
  gastosExtraordinarios: 'Gastos extraordinarios',
  resultadoActividadesExtraordinarias: 'Resultado actividades extraordinarias',
  resultadoEjercicio: 'Resultado del ejercicio',
}]